name: shortway
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.2+1
  dartz: ^0.10.1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  equatable: ^2.0.5
  get_it: ^7.6.8

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1
  mockito: ^5.4.4

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true